# uses: https://github.com/marketplace/actions/merge-pull-requests-automerge-action
name: Automerge Submodules
on:
#   pull_request:
#     types:
#       - labeled
#       - unlabeled
#       - synchronize
#       - opened
#       - edited
#       - ready_for_review
#       - reopened
#       - unlocked
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.EMILYHUNT_WORKFLOWS }}"
          MERGE_FILTER_AUTHOR: "emilyhunt"
          # MERGE_LABELS: "automerge"
          MERGE_LABELS: "!dontmerge"
          MERGE_DELETE_BRANCH: true
          UPDATE_LABELS: "!dontmerge"
