# Auto-approve new PRs https://github.com/marketplace/actions/auto-approve
name: Auto approve
on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'github-actions'
    steps:
      - uses: hmarr/auto-approve-action@v3
